[project]
name = "brainf"
version = "0.0.0"
description = "Compiler and codesign infrastructure for the Brainfuck language"
authors = [{ name = "Matteo Mei" }]

requires-python = ">3.10"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = [
  'brainf',
  'brainf.opt',
  'brainf.codegen',
]
